"""add missing default_city and default_country to businesses

Revision ID: 05c9109a5762
Revises: 1991184cd4a9
Create Date: 2026-01-27 18:59:38.165609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c9109a5762'
down_revision: Union[str, Sequence[str], None] = '1991184cd4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('default_country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('default_country')
        batch_op.drop_column('default_city')
    # ### end Alembic commands ###
