"""Initial schema fresh

Revision ID: 141b45aa0f4b
Revises:
Create Date: 2026-01-31 17:11:02.203493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models.base_enum


# revision identifiers, used by Alembic.
revision: str = "141b45aa0f4b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("payment_link", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column(
            "subscription_status", sa.String(), nullable=False
        ),
        sa.Column("seat_limit", sa.Integer(), nullable=False),
        sa.Column("active_addons", sa.JSON(), nullable=False),
        sa.Column("quickbooks_connected", sa.Boolean(), nullable=False),
        sa.Column("quickbooks_last_sync", sa.DateTime(), nullable=True),
        sa.Column("clerk_org_id", sa.String(), nullable=True),
        sa.Column(
            "workflow_invoicing", sa.String(), nullable=True
        ),
        sa.Column("workflow_quoting", sa.String(), nullable=True),
        sa.Column(
            "workflow_payment_timing", sa.String(), nullable=True
        ),
        sa.Column("workflow_tax_inclusive", sa.Boolean(), nullable=True),
        sa.Column("workflow_include_payment_terms", sa.Boolean(), nullable=True),
        sa.Column("workflow_enable_reminders", sa.Boolean(), nullable=True),
        sa.Column("workflow_show_whatsapp_button", sa.Boolean(), nullable=True),
        sa.Column("workflow_pipeline_quoted_stage", sa.Boolean(), nullable=False),
        sa.Column(
            "workflow_job_creation_default",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "workflow_distance_unit", sa.String(), nullable=False
        ),
        sa.Column("workflow_auto_quote_followup", sa.Boolean(), nullable=False),
        sa.Column("workflow_quote_followup_delay_hrs", sa.Integer(), nullable=False),
        sa.Column("workflow_auto_review_requests", sa.Boolean(), nullable=False),
        sa.Column("workflow_review_request_delay_hrs", sa.Integer(), nullable=False),
        sa.Column("workflow_review_link", sa.String(), nullable=True),
        sa.Column("marketing_settings", sa.JSON(), nullable=False),
        sa.Column("messenger_settings", sa.JSON(), nullable=True),
        sa.Column("default_city", sa.String(), nullable=True),
        sa.Column("default_country", sa.String(), nullable=True),
        sa.Column("default_tax_rate", sa.Float(), nullable=False),
        sa.Column("invite_code", sa.String(length=20), nullable=True),
        sa.Column("message_count_current_period", sa.Integer(), nullable=False),
        sa.Column("billing_cycle_anchor", sa.DateTime(), nullable=True),
        sa.Column("message_credits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clerk_org_id"),
    )
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_businesses_invite_code"), ["invite_code"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_businesses_name"), ["name"], unique=False)

    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("template_id", sa.String(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("recipient_query", sa.String(), nullable=True),
        sa.Column("total_recipients", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaigns_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_campaigns_name"), ["name"], unique=False)

    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("postal_code", sa.String(), nullable=True),
        sa.Column("original_address_input", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("pipeline_stage", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("quickbooks_id", sa.String(length=50), nullable=True),
        sa.Column("quickbooks_synced_at", sa.DateTime(), nullable=True),
        sa.Column(
            "quickbooks_sync_status", sa.String(), nullable=True
        ),
        sa.Column("quickbooks_sync_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customers_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_customers_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_customers_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_customers_quickbooks_id"), ["quickbooks_id"], unique=False
        )

    op.create_table(
        "export_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=True),
        sa.Column("public_url", sa.String(), nullable=True),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("export_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_export_requests_business_id"), ["business_id"], unique=False
        )

    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("error_log", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_jobs_business_id"), ["business_id"], unique=False
        )

    op.create_table(
        "integration_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("INBOUND_KEY", "META_CAPI", "WEBHOOK", name="integrationtype"),
            nullable=False,
        ),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("key_hash", sa.String(), nullable=True),
        sa.Column("config_payload", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("integration_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_integration_configs_business_id"),
            ["business_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_integration_configs_key_hash"), ["key_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_integration_configs_type"), ["type"], unique=False
        )

    op.create_table(
        "message_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=True),
        sa.Column("recipient_phone", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("message_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("trigger_source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("log_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_message_logs_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_logs_recipient_phone"),
            ["recipient_phone"],
            unique=False,
        )

    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_price", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("estimated_duration", sa.Integer(), nullable=False),
        sa.Column("quickbooks_id", sa.String(length=50), nullable=True),
        sa.Column("quickbooks_synced_at", sa.DateTime(), nullable=True),
        sa.Column(
            "quickbooks_sync_status", sa.String(), nullable=True
        ),
        sa.Column("quickbooks_sync_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_services_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_services_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_services_quickbooks_id"), ["quickbooks_id"], unique=False
        )

    op.create_table(
        "sync_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("sync_timestamp", sa.DateTime(), nullable=False),
        sa.Column("sync_type", sa.String(), nullable=False),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("records_succeeded", sa.Integer(), nullable=False),
        sa.Column("records_failed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_logs_business_id"), ["business_id"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "preferred_channel", sa.String(), nullable=False
        ),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("default_start_location_lat", sa.Float(), nullable=True),
        sa.Column("default_start_location_lng", sa.Float(), nullable=True),
        sa.Column("google_calendar_credentials", sa.JSON(), nullable=True),
        sa.Column("google_calendar_sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("clerk_id", sa.String(), nullable=True),
        sa.Column("current_latitude", sa.Float(), nullable=True),
        sa.Column("current_longitude", sa.Float(), nullable=True),
        sa.Column("location_updated_at", sa.DateTime(), nullable=True),
        sa.Column("current_shift_start", sa.DateTime(), nullable=True),
        sa.Column("geocoding_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clerk_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_business_id"), ["business_id"], unique=False
        )

    op.create_table(
        "whatsapp_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "MARKETING",
                "UTILITY",
                "AUTHENTICATION",
                name="whatsapptemplatecategory",
            ),
            nullable=False,
        ),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "PAUSED",
                "DISABLED",
                "DRAFT",
                name="whatsapptemplatestatus",
            ),
            nullable=False,
        ),
        sa.Column("meta_template_id", sa.String(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("whatsapp_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_whatsapp_templates_business_id"),
            ["business_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_whatsapp_templates_meta_template_id"),
            ["meta_template_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_whatsapp_templates_name"), ["name"], unique=False
        )

    op.create_table(
        "campaign_recipients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campaign_recipients", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campaign_recipients_campaign_id"),
            ["campaign_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_campaign_recipients_customer_id"),
            ["customer_id"],
            unique=False,
        )

    op.create_table(
        "conversation_states",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("draft_data", sa.JSON(), nullable=True),
        sa.Column("last_action_metadata", sa.JSON(), nullable=True),
        sa.Column("pending_action_timestamp", sa.DateTime(), nullable=True),
        sa.Column("pending_action_payload", sa.JSON(), nullable=True),
        sa.Column("active_channel", sa.String(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "customer_availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer_availability", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customer_availability_customer_id"),
            ["customer_id"],
            unique=False,
        )

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("public_url", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column(
            "doc_type",
            sa.Enum("INTERNAL", "CUSTOMER_UPLOAD", "GENERATED", name="documenttype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_documents_customer_id"), ["customer_id"], unique=False
        )

    op.create_table(
        "invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("inviter_id", sa.Integer(), nullable=False),
        sa.Column("invitee_identifier", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invitations_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invitations_invitee_identifier"),
            ["invitee_identifier"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_invitations_inviter_id"), ["inviter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invitations_token"), ["token"], unique=True
        )

    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("subtotal", sa.Float(), nullable=True),
        sa.Column("tax_amount", sa.Float(), nullable=True),
        sa.Column("tax_rate", sa.Float(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("postal_code", sa.String(), nullable=True),
        sa.Column("paid", sa.Boolean(), nullable=False),
        sa.Column("gcal_event_id", sa.String(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("estimated_duration", sa.Integer(), nullable=False),
        sa.Column("begun_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("total_actual_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_jobs_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_jobs_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_jobs_employee_id"), ["employee_id"], unique=False
        )

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("from_number", sa.String(), nullable=False),
        sa.Column("to_number", sa.String(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("channel_type", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("is_executed", sa.Boolean(), nullable=False),
        sa.Column("log_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_messages_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_messages_from_number"), ["from_number"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_messages_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("urgency", sa.String(), nullable=False),
        sa.Column("expected_value", sa.Float(), nullable=True),
        sa.Column("subtotal", sa.Float(), nullable=False),
        sa.Column("tax_amount", sa.Float(), nullable=False),
        sa.Column("tax_rate", sa.Float(), nullable=False),
        sa.Column("follow_up_date", sa.DateTime(), nullable=True),
        sa.Column("customer_details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requests_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_requests_customer_id"), ["customer_id"], unique=False
        )

    op.create_table(
        "wage_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.Column("rate_value", sa.Float(), nullable=False),
        sa.Column("tax_withholding_rate", sa.Float(), nullable=False),
        sa.Column("allow_expense_claims", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("receipt_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_expenses_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_expenses_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_expenses_job_id"), ["job_id"], unique=False
        )

    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("public_url", sa.String(), nullable=False),
        sa.Column("payment_link", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("quickbooks_id", sa.String(length=50), nullable=True),
        sa.Column("quickbooks_synced_at", sa.DateTime(), nullable=True),
        sa.Column(
            "quickbooks_sync_status", sa.String(), nullable=True
        ),
        sa.Column("quickbooks_sync_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invoices_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invoices_quickbooks_id"), ["quickbooks_id"], unique=False
        )

    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("entry_type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ledger_entries_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ledger_entries_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ledger_entries_job_id"), ["job_id"], unique=False
        )

    op.create_table(
        "line_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("line_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_line_items_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_line_items_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_line_items_service_id"), ["service_id"], unique=False
        )

    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("subtotal", sa.Float(), nullable=False),
        sa.Column("tax_amount", sa.Float(), nullable=False),
        sa.Column("tax_rate", sa.Float(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("external_token", sa.String(), nullable=False),
        sa.Column("blob_url", sa.String(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("quickbooks_id", sa.String(length=50), nullable=True),
        sa.Column("quickbooks_synced_at", sa.DateTime(), nullable=True),
        sa.Column(
            "quickbooks_sync_status", sa.String(), nullable=True
        ),
        sa.Column("quickbooks_sync_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quotes_business_id"), ["business_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quotes_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quotes_external_token"), ["external_token"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_quotes_quickbooks_id"), ["quickbooks_id"], unique=False
        )

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("payment_date", sa.DateTime(), nullable=False),
        sa.Column("payment_method", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("quickbooks_id", sa.String(length=50), nullable=True),
        sa.Column("quickbooks_synced_at", sa.DateTime(), nullable=True),
        sa.Column(
            "quickbooks_sync_status", sa.String(), nullable=True
        ),
        sa.Column("quickbooks_sync_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payments_invoice_id"), ["invoice_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payments_quickbooks_id"), ["quickbooks_id"], unique=False
        )

    op.create_table(
        "quote_line_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quote_line_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quote_line_items_quote_id"), ["quote_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quote_line_items_service_id"), ["service_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quote_line_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quote_line_items_service_id"))
        batch_op.drop_index(batch_op.f("ix_quote_line_items_quote_id"))

    op.drop_table("quote_line_items")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_quickbooks_id"))
        batch_op.drop_index(batch_op.f("ix_payments_invoice_id"))

    op.drop_table("payments")
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quotes_quickbooks_id"))
        batch_op.drop_index(batch_op.f("ix_quotes_external_token"))
        batch_op.drop_index(batch_op.f("ix_quotes_customer_id"))
        batch_op.drop_index(batch_op.f("ix_quotes_business_id"))

    op.drop_table("quotes")
    with op.batch_alter_table("line_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_line_items_service_id"))
        batch_op.drop_index(batch_op.f("ix_line_items_request_id"))
        batch_op.drop_index(batch_op.f("ix_line_items_job_id"))

    op.drop_table("line_items")
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ledger_entries_job_id"))
        batch_op.drop_index(batch_op.f("ix_ledger_entries_employee_id"))
        batch_op.drop_index(batch_op.f("ix_ledger_entries_business_id"))

    op.drop_table("ledger_entries")
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoices_quickbooks_id"))
        batch_op.drop_index(batch_op.f("ix_invoices_job_id"))

    op.drop_table("invoices")
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expenses_job_id"))
        batch_op.drop_index(batch_op.f("ix_expenses_employee_id"))
        batch_op.drop_index(batch_op.f("ix_expenses_business_id"))

    op.drop_table("expenses")
    op.drop_table("wage_configurations")
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requests_customer_id"))
        batch_op.drop_index(batch_op.f("ix_requests_business_id"))

    op.drop_table("requests")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_user_id"))
        batch_op.drop_index(batch_op.f("ix_messages_from_number"))
        batch_op.drop_index(batch_op.f("ix_messages_business_id"))

    op.drop_table("messages")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_employee_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_customer_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_business_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invitations_token"))
        batch_op.drop_index(batch_op.f("ix_invitations_inviter_id"))
        batch_op.drop_index(batch_op.f("ix_invitations_invitee_identifier"))
        batch_op.drop_index(batch_op.f("ix_invitations_business_id"))

    op.drop_table("invitations")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_customer_id"))

    op.drop_table("documents")
    with op.batch_alter_table("customer_availability", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_availability_customer_id"))

    op.drop_table("customer_availability")
    op.drop_table("conversation_states")
    with op.batch_alter_table("campaign_recipients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_recipients_customer_id"))
        batch_op.drop_index(batch_op.f("ix_campaign_recipients_campaign_id"))

    op.drop_table("campaign_recipients")
    with op.batch_alter_table("whatsapp_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_whatsapp_templates_name"))
        batch_op.drop_index(batch_op.f("ix_whatsapp_templates_meta_template_id"))
        batch_op.drop_index(batch_op.f("ix_whatsapp_templates_business_id"))

    op.drop_table("whatsapp_templates")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_business_id"))

    op.drop_table("users")
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_logs_business_id"))

    op.drop_table("sync_logs")
    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_services_quickbooks_id"))
        batch_op.drop_index(batch_op.f("ix_services_name"))
        batch_op.drop_index(batch_op.f("ix_services_business_id"))

    op.drop_table("services")
    with op.batch_alter_table("message_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_logs_recipient_phone"))
        batch_op.drop_index(batch_op.f("ix_message_logs_business_id"))

    op.drop_table("message_logs")
    with op.batch_alter_table("integration_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_integration_configs_type"))
        batch_op.drop_index(batch_op.f("ix_integration_configs_key_hash"))
        batch_op.drop_index(batch_op.f("ix_integration_configs_business_id"))

    op.drop_table("integration_configs")
    with op.batch_alter_table("import_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_jobs_business_id"))

    op.drop_table("import_jobs")
    with op.batch_alter_table("export_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_export_requests_business_id"))

    op.drop_table("export_requests")
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customers_quickbooks_id"))
        batch_op.drop_index(batch_op.f("ix_customers_name"))
        batch_op.drop_index(batch_op.f("ix_customers_email"))
        batch_op.drop_index(batch_op.f("ix_customers_business_id"))

    op.drop_table("customers")
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaigns_name"))
        batch_op.drop_index(batch_op.f("ix_campaigns_business_id"))

    op.drop_table("campaigns")
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_businesses_name"))
        batch_op.drop_index(batch_op.f("ix_businesses_invite_code"))

    op.drop_table("businesses")
    # ### end Alembic commands ###
