"""convert_job_status_to_enum_and_add_time_tracking_fields

Revision ID: 1aa4956d4ba0
Revises: 54053f5fba26
Create Date: 2026-01-27 18:14:06.536985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1aa4956d4ba0"
down_revision: Union[str, Sequence[str], None] = "54053f5fba26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total_actual_duration_seconds",
                sa.Integer(),
                server_default="0",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("total_actual_duration_seconds")

    # ### end Alembic commands ###
