"""add tax fields to requests

Revision ID: 1abd88715542
Revises: 4f6b0bb70a40
Create Date: 2026-01-28 09:53:38.649602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1abd88715542"
down_revision: Union[str, Sequence[str], None] = "4f6b0bb70a40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "subtotal", sa.Float(), nullable=False, server_default=sa.text("0.0")
            )
        )
        batch_op.add_column(
            sa.Column(
                "tax_amount", sa.Float(), nullable=False, server_default=sa.text("0.0")
            )
        )
        batch_op.add_column(
            sa.Column(
                "tax_rate", sa.Float(), nullable=False, server_default=sa.text("0.0")
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_column("tax_rate")
        batch_op.drop_column("tax_amount")
        batch_op.drop_column("subtotal")

    # ### end Alembic commands ###
