"""unified_search_schema_sync

Revision ID: 1e58b1245832
Revises: d0fc74b373af
Create Date: 2026-01-26 17:56:23.429714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e58b1245832"
down_revision: Union[str, Sequence[str], None] = "d0fc74b373af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_businesses_clerk_org_id"))
        batch_op.create_unique_constraint(
            "uq_businesses_clerk_org_id", ["clerk_org_id"]
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_jobs_customer_id"), ["customer_id"], unique=False
        )

    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_clerk_id"))
        batch_op.create_index(
            batch_op.f("ix_users_business_id"), ["business_id"], unique=False
        )
        batch_op.create_unique_constraint("uq_users_clerk_id", ["clerk_id"])

    with op.batch_alter_table("wage_configurations", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wage_configurations", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_clerk_id", type_="unique")
        batch_op.drop_index(batch_op.f("ix_users_business_id"))
        batch_op.create_index(batch_op.f("ix_users_clerk_id"), ["clerk_id"], unique=1)

    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_customer_id"))

    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_constraint("uq_businesses_clerk_org_id", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_businesses_clerk_org_id"), ["clerk_org_id"], unique=1
        )

    # ### end Alembic commands ###
