"""add_business_id_to_message_log

Revision ID: 1ea69c57842f
Revises: 3c95e5003d01
Create Date: 2026-01-22 10:51:36.604550

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ea69c57842f"
down_revision: Union[str, Sequence[str], None] = "3c95e5003d01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("message_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("business_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_message_logs_business_id"), ["business_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_message_logs_business_id", "businesses", ["business_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message_logs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_message_logs_business_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_message_logs_business_id"))
        batch_op.drop_column("business_id")
    # ### end Alembic commands ###
