"""add error_log to export_requests

Revision ID: 271d1fde1f13
Revises: 1abd88715542
Create Date: 2026-01-28 11:35:48.980298

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "271d1fde1f13"
down_revision: Union[str, Sequence[str], None] = "1abd88715542"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("export_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error_log", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("export_requests", schema=None) as batch_op:
        batch_op.drop_column("error_log")

    # ### end Alembic commands ###
