"""add_autoroute_foundations

Revision ID: 29d4b35bbedf
Revises: 2e4dc444ed6e
Create Date: 2026-01-21 09:36:06.477890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29d4b35bbedf"
down_revision: Union[str, Sequence[str], None] = "2e4dc444ed6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient_phone", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("WHATSAPP", "SMS", name="messagetype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", name="messagestatus"),
            nullable=False,
        ),
        sa.Column("trigger_source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_logs_recipient_phone"),
        "message_logs",
        ["recipient_phone"],
        unique=False,
    )
    op.create_table(
        "customer_availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("is_available", sa.Boolean(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_availability_customer_id"),
        "customer_availability",
        ["customer_id"],
        unique=False,
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("public_url", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_job_id"), "invoices", ["job_id"], unique=False)

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "estimated_duration", sa.Integer(), server_default="60", nullable=False
            )
        )
        batch_op.add_column(sa.Column("employee_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_jobs_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_jobs_employee_id", "users", ["employee_id"], ["id"]
        )

    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "estimated_duration", sa.Integer(), server_default="60", nullable=False
            )
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("default_start_location_lat", sa.Float(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("default_start_location_lng", sa.Float(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("default_start_location_lng")
        batch_op.drop_column("default_start_location_lat")
        batch_op.drop_column("name")

    with op.batch_alter_table("services", schema=None) as batch_op:
        batch_op.drop_column("estimated_duration")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_jobs_employee_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_jobs_employee_id"))
        batch_op.drop_column("employee_id")
        batch_op.drop_column("estimated_duration")

    op.drop_index(op.f("ix_invoices_job_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(
        op.f("ix_customer_availability_customer_id"), table_name="customer_availability"
    )
    op.drop_table("customer_availability")
    op.drop_index(op.f("ix_message_logs_recipient_phone"), table_name="message_logs")
    op.drop_table("message_logs")
    # ### end Alembic commands ###
