"""add_usage_billing_fields

Revision ID: 3c95e5003d01
Revises: 2e4dc444ed6e
Create Date: 2026-01-22 10:50:01.943299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c95e5003d01"
down_revision: Union[str, Sequence[str], None] = "2e4dc444ed6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesses",
        sa.Column(
            "message_count_current_period",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "businesses", sa.Column("billing_cycle_anchor", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesses", "billing_cycle_anchor")
    op.drop_column("businesses", "message_count_current_period")
    # ### end Alembic commands ###
