"""add_missing_schema_fields

Revision ID: 41fcf56c35b7
Revises: fa32e02855f9
Create Date: 2026-01-31 15:57:14.654223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41fcf56c35b7"
down_revision: Union[str, Sequence[str], None] = "fa32e02855f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("last_name", sa.String(), nullable=True))

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subtotal", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("tax_amount", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("tax_rate", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("gcal_event_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("begun_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("completed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "total_actual_duration_seconds",
                sa.Integer(),
                nullable=False,
                server_default="0",
            )
        )

    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.Text(), nullable=False, server_default="")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_column("description")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("total_actual_duration_seconds")
        batch_op.drop_column("completed_at")
        batch_op.drop_column("begun_at")
        batch_op.drop_column("gcal_event_id")
        batch_op.drop_column("tax_rate")
        batch_op.drop_column("tax_amount")
        batch_op.drop_column("subtotal")

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
