"""Add quote tables

Revision ID: 4224dc58bdff
Revises: 5badbf80194d
Create Date: 2026-01-20 18:23:16.500449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4224dc58bdff"
down_revision: Union[str, Sequence[str], None] = "5badbf80194d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "SENT", "ACCEPTED", "REJECTED", "EXPIRED", name="quotestatus"
            ),
            nullable=False,
        ),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("external_token", sa.String(), nullable=False),
        sa.Column("blob_url", sa.String(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quotes_business_id"), "quotes", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_quotes_customer_id"), "quotes", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_quotes_external_token"), "quotes", ["external_token"], unique=True
    )
    op.create_table(
        "quote_line_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quote_line_items_quote_id"),
        "quote_line_items",
        ["quote_id"],
        unique=False,
    )
    with op.batch_alter_table("conversation_states", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("pending_action_timestamp", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("pending_action_payload", sa.JSON(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "active_channel", sa.String(), nullable=False, server_default="whatsapp"
            )
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_messages_user_id", "users", ["user_id"], ["id"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "preferred_channel",
                sa.String(),
                nullable=False,
                server_default="whatsapp",
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "preferred_channel")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("conversation_states", "active_channel")
    op.drop_column("conversation_states", "pending_action_payload")
    op.drop_column("conversation_states", "pending_action_timestamp")
    op.drop_index(op.f("ix_quote_line_items_quote_id"), table_name="quote_line_items")
    op.drop_table("quote_line_items")
    op.drop_index(op.f("ix_quotes_external_token"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_customer_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_business_id"), table_name="quotes")
    op.drop_table("quotes")
    # ### end Alembic commands ###
