"""Add payment link to Business and Invoice

Revision ID: 4585b682f5c3
Revises: c91fa85524a7
Create Date: 2026-01-22 10:46:44.805516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4585b682f5c3"
down_revision: Union[str, Sequence[str], None] = "c91fa85524a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_link", sa.String(), nullable=True))

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_link", sa.String(), nullable=True))

    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_logs_business_timestamp"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_logs_business_timestamp"),
            ["business_id", "sync_timestamp"],
            unique=False,
        )

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_column("payment_link")

    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_column("payment_link")

    # ### end Alembic commands ###
