"""add quoted pipeline stage and setting

Revision ID: 4f6b0bb70a40
Revises: be94ccad16f3
Create Date: 2026-01-28 09:28:12.424056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f6b0bb70a40"
down_revision: Union[str, Sequence[str], None] = "be94ccad16f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "workflow_pipeline_quoted_stage",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("1"),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_column("workflow_pipeline_quoted_stage")

    # ### end Alembic commands ###
