"""add geocoding_count to user

Revision ID: 54053f5fba26
Revises: b5b76fa9bad1
Create Date: 2026-01-27 17:05:42.839094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54053f5fba26'
down_revision: Union[str, Sequence[str], None] = 'b5b76fa9bad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('workflow_distance_unit',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'mi'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geocoding_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('geocoding_count')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('workflow_distance_unit',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'mi'"))

    # ### end Alembic commands ###
