"""Add request_id to line_items and remove expected_line_items

Revision ID: 54c5e61f6b84
Revises: 630bde8a1bda
Create Date: 2026-01-28 09:11:55.775467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54c5e61f6b84"
down_revision: Union[str, Sequence[str], None] = "630bde8a1bda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("line_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("request_id", sa.Integer(), nullable=True))
        batch_op.alter_column("job_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_line_items_request_id"), ["request_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_line_items_request_id_requests", "requests", ["request_id"], ["id"]
        )

    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.drop_column("expected_line_items")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("expected_line_items", sa.VARCHAR(), nullable=True)
        )

    with op.batch_alter_table("line_items", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_line_items_request_id"))
        batch_op.alter_column("job_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("request_id")

    # ### end Alembic commands ###
