"""rename MessageLog metadata to log_metadata

Revision ID: 5f1ef1cd99de
Revises: f6cf5d09d65c
Create Date: 2026-01-26 20:12:45.804455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f1ef1cd99de"
down_revision: Union[str, Sequence[str], None] = "f6cf5d09d65c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "workflow_auto_quote_followup",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "workflow_quote_followup_delay_hrs",
                sa.Integer(),
                nullable=False,
                server_default="48",
            )
        )
        batch_op.add_column(
            sa.Column(
                "workflow_auto_review_requests",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "workflow_review_request_delay_hrs",
                sa.Integer(),
                nullable=False,
                server_default="2",
            )
        )
        batch_op.add_column(
            sa.Column("workflow_review_link", sa.String(), nullable=True)
        )
        batch_op.alter_column(
            "workflow_job_creation_default",
            existing_type=sa.VARCHAR(length=13),
            type_=sa.Enum(
                "MARK_DONE",
                "UNSCHEDULED",
                "AUTO_SCHEDULE",
                "SCHEDULED_TODAY",
                name="jobcreationdefault",
            ),
            existing_nullable=True,
        )
        batch_op.drop_index(batch_op.f("ux_businesses_clerk_org_id"))
        batch_op.create_unique_constraint(
            "uq_businesses_clerk_org_id", ["clerk_org_id"]
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_executed", sa.Boolean(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ux_users_clerk_id"))
        batch_op.create_unique_constraint("uq_users_clerk_id", ["clerk_id"])

    with op.batch_alter_table("wage_configurations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "allow_expense_claims", sa.Boolean(), nullable=False, server_default="1"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wage_configurations", schema=None) as batch_op:
        batch_op.drop_column("allow_expense_claims")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_index(batch_op.f("ux_users_clerk_id"), ["clerk_id"], unique=1)

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_column("is_executed")

    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_index(
            batch_op.f("ux_businesses_clerk_org_id"), ["clerk_org_id"], unique=1
        )
        batch_op.alter_column(
            "workflow_job_creation_default",
            existing_type=sa.Enum(
                "MARK_DONE",
                "UNSCHEDULED",
                "AUTO_SCHEDULE",
                "SCHEDULED_TODAY",
                name="jobcreationdefault",
            ),
            type_=sa.VARCHAR(length=13),
            existing_nullable=True,
        )
        batch_op.drop_column("workflow_review_link")
        batch_op.drop_column("workflow_review_request_delay_hrs")
        batch_op.drop_column("workflow_auto_review_requests")
        batch_op.drop_column("workflow_quote_followup_delay_hrs")
        batch_op.drop_column("workflow_auto_quote_followup")

    # ### end Alembic commands ###
