"""add_whatsapp_templates

Revision ID: 67796f9c22c7
Revises: 05c9109a5762
Create Date: 2026-01-27 19:45:40.799092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67796f9c22c7"
down_revision: Union[str, Sequence[str], None] = "05c9109a5762"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatsapp_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "MARKETING",
                "UTILITY",
                "AUTHENTICATION",
                name="whatsapptemplatecategory",
            ),
            nullable=False,
        ),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "PAUSED",
                "DISABLED",
                "DRAFT",
                name="whatsapptemplatestatus",
            ),
            nullable=False,
        ),
        sa.Column("meta_template_id", sa.String(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("whatsapp_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_whatsapp_templates_business_id"),
            ["business_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_whatsapp_templates_meta_template_id"),
            ["meta_template_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_whatsapp_templates_name"), ["name"], unique=False
        )

    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "marketing_settings", sa.JSON(), nullable=False, server_default="{}"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_column("marketing_settings")

    with op.batch_alter_table("whatsapp_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_whatsapp_templates_name"))
        batch_op.drop_index(batch_op.f("ix_whatsapp_templates_meta_template_id"))
        batch_op.drop_index(batch_op.f("ix_whatsapp_templates_business_id"))

    op.drop_table("whatsapp_templates")
    # ### end Alembic commands ###
