"""add company_name to customers

Revision ID: 77c1bd6c25ea
Revises: 108020504ecb
Create Date: 2026-01-29 18:56:43.747285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77c1bd6c25ea"
down_revision: Union[str, Sequence[str], None] = "108020504ecb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("company_name", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_column("company_name")

    # ### end Alembic commands ###
