"""add default_city and default_country to business

Revision ID: abd1582ebbef
Revises: f16b6842998a
Create Date: 2026-01-27 07:00:41.277237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abd1582ebbef"
down_revision: Union[str, Sequence[str], None] = "f16b6842998a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subtotal", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("tax_amount", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("tax_rate", sa.Float(), nullable=True))

    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subtotal", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("tax_amount", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("tax_rate", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.drop_column("tax_rate")
        batch_op.drop_column("tax_amount")
        batch_op.drop_column("subtotal")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("tax_rate")
        batch_op.drop_column("tax_amount")
        batch_op.drop_column("subtotal")

    # ### end Alembic commands ###
