"""add_postal_code

Revision ID: b68725d2ef2b
Revises: 29221d00596e
Create Date: 2026-01-17 21:02:15.315054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b68725d2ef2b"
down_revision: Union[str, Sequence[str], None] = "4a2fe5d1fdc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("postal_code", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("postal_code", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "postal_code")
    op.drop_column("customers", "postal_code")
    # ### end Alembic commands ###
