"""add invite_code to business

Revision ID: bcb62950c550
Revises: abd1582ebbef
Create Date: 2026-01-27 07:10:59.312706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcb62950c550"
down_revision: Union[str, Sequence[str], None] = "abd1582ebbef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("invite_code", sa.String(length=20), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_businesses_invite_code"), ["invite_code"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_businesses_invite_code"))
        batch_op.drop_column("invite_code")

    # ### end Alembic commands ###
