"""Convert Request.urgency to Enum

Revision ID: be94ccad16f3
Revises: 54c5e61f6b84
Create Date: 2026-01-28 09:17:39.210504

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "be94ccad16f3"
down_revision: Union[str, Sequence[str], None] = "54c5e61f6b84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
