"""add business_id to ledger_entries

Revision ID: c387f4daf483
Revises: 77c1bd6c25ea
Create Date: 2026-01-30 18:00:27.733280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c387f4daf483"
down_revision: Union[str, Sequence[str], None] = "77c1bd6c25ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("business_id", sa.Integer(), nullable=False, server_default="1")
        )
        batch_op.create_index(
            batch_op.f("ix_ledger_entries_business_id"), ["business_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_ledger_entries_business_id", "businesses", ["business_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_entries", schema=None) as batch_op:
        batch_op.drop_constraint("fk_ledger_entries_business_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_ledger_entries_business_id"))
        batch_op.drop_column("business_id")

    # ### end Alembic commands ###
