"""add allow_expense_claims to wage_config

Revision ID: d0fc74b373af
Revises: d1234567890b
Create Date: 2026-01-26 17:18:09.183244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0fc74b373af"
down_revision: Union[str, Sequence[str], None] = "d1234567890b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wage_configurations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "allow_expense_claims", sa.Boolean(), nullable=False, server_default="1"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wage_configurations", schema=None) as batch_op:
        batch_op.drop_column("allow_expense_claims")

    # ### end Alembic commands ###
