"""add_user_location_fields

Revision ID: d4289d247dac
Revises: 2e4dc444ed6e
Create Date: 2026-01-21 10:54:02.599273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4289d247dac"
down_revision: Union[str, Sequence[str], None] = "2e4dc444ed6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("current_latitude", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("current_longitude", sa.Float(), nullable=True))
    op.add_column(
        "users", sa.Column("location_updated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "location_updated_at")
    op.drop_column("users", "current_longitude")
    op.drop_column("users", "current_latitude")
    # ### end Alembic commands ###
