"""add default tax rate to business

Revision ID: df5b326b5967
Revises: bcb62950c550
Create Date: 2026-01-27 07:56:43.132805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5b326b5967'
down_revision: Union[str, Sequence[str], None] = 'bcb62950c550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_tax_rate', sa.Float(), nullable=False, server_default="0.0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('default_tax_rate')

    # ### end Alembic commands ###
