"""add_integration_configs_table

Revision ID: e6aaeed9435c
Revises: 29d4b35bbedf
Create Date: 2026-01-21 14:03:08.642057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6aaeed9435c"
down_revision: Union[str, Sequence[str], None] = "29d4b35bbedf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("INBOUND_KEY", "META_CAPI", "WEBHOOK", name="integrationtype"),
            nullable=False,
        ),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("key_hash", sa.String(), nullable=True),
        sa.Column("config_payload", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("integration_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_integration_configs_business_id"),
            ["business_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_integration_configs_key_hash"), ["key_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_integration_configs_type"), ["type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("integration_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_integration_configs_type"))
        batch_op.drop_index(batch_op.f("ix_integration_configs_key_hash"))
        batch_op.drop_index(batch_op.f("ix_integration_configs_business_id"))

    op.drop_table("integration_configs")
    # ### end Alembic commands ###
