"""update requests table

Revision ID: f16b6842998a
Revises: 5f1ef1cd99de
Create Date: 2026-01-27 06:19:56.126765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f16b6842998a"
down_revision: Union[str, Sequence[str], None] = "5f1ef1cd99de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("customer_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("urgency", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("expected_value", sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column("expected_line_items", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("follow_up_date", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("customer_details", sa.JSON(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_requests_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_requests_customer_id", "customers", ["customer_id"], ["id"]
        )
        batch_op.drop_column("content")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("content", sa.TEXT(), nullable=False))
        batch_op.drop_constraint("fk_requests_customer_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_requests_customer_id"))
        batch_op.drop_column("customer_details")
        batch_op.drop_column("follow_up_date")
        batch_op.drop_column("expected_line_items")
        batch_op.drop_column("expected_value")
        batch_op.drop_column("urgency")
        batch_op.drop_column("description")
        batch_op.drop_column("customer_id")

    # ### end Alembic commands ###
