"""add workflow_show_whatsapp_button

Revision ID: f71c2f67e64c
Revises: 1e58b1245832
Create Date: 2026-01-26 19:38:11.486027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71c2f67e64c'
down_revision: Union[str, Sequence[str], None] = '1e58b1245832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_show_whatsapp_button', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('workflow_show_whatsapp_button')

    # ### end Alembic commands ###
