"""add messenger_settings to business

Revision ID: fa32e02855f9
Revises: c387f4daf483
Create Date: 2026-01-30 19:20:41.192229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa32e02855f9'
down_revision: Union[str, Sequence[str], None] = 'c387f4daf483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messenger_settings', sa.JSON(), nullable=True, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('messenger_settings')

    # ### end Alembic commands ###
